//Must Sync Background & Popup
export const ENCRYPTED_WALLET = 'ew'
export const CURRENT_ADDRESS = 'ca'
export const ACCOUNTS = 'accounts'
export const PRIMARY_ADDRESS = 'pa';
export const TXS = 'txs'
export const PASSPHRASE = 'pp'
export const NETWORKS = 'n';
export const CURRENT_NETWORK = 'cn';
