//Must Sync Background & Popup
export const ENCRYPTED_WALLET = 'ew'
export const CURRENT_ADDRESS = 'ca'
export const ACCOUNTS = 'accounts'
export const TXS = 'txs'
export const PASSPHRASE = 'pp'
export const APPROVAL_REQUESTS = 'approval_requests';
export const CONNECTED_SITES = 'connected_sites';
export const NETWORKS = 'n';
export const CURRENT_NETWORK = 'cn';
